name: Build
on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/build.yml'
jobs:
  build-project:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - name: Install PugiXML
        run: sudo apt-get install libpugixml-dev
      - name: Install GLFW
        run: sudo apt-get install libglfw3-dev
      - name: Install Assimp
        run: sudo apt-get install libassimp-dev
      - name: Checkout
        uses: actions/checkout@v4.1.2
      - name: Configure and Build Project
        uses: threeal/cmake-action@main
        with:
          c-compiler: clang
          cxx-compiler: clang++
          source-dir: ./src
          options: CMAKE_BUILD_TYPE=Release
          build-args: --config Release
          cxx-flags: -stdlib=libc++ -std=c++20
      - name: Create build directory
        run: mkdir ./final-build
      - name: Copy assets
        run: cp -r ./Assets ./final-build/Assets
      - name: Copy executable
        run: cp -r ./src/build/TheFrim ./final-build
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: The Frim (Linux Release)
          path: ./final-build