name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cmake configure
      run: cmake -B build
      working-directory: ./src
    - name: cmake build
      run: cmake --build build
    - uses: actions/upload-artifact@v4
      with:
        name: frim
        path: build
