name: Build
on:
  push:
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Install PugiXML
        run: sudo apt-get install libpugixml-dev
      - name: Install IMGUI
        run: sudo apt-get install libimgui-dev
      - name: Install GLFW
        run: sudo apt-get install libglfw3-dev
      - name: Install Miniz
        run: sudo apt-get install libminizip1
      - name: Install Assimp
        run: sudo apt-get install libassimp-dev
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v4
      
      - name: Configure and Build Project
        uses: threeal/cmake-action@main
        with:
          generator: Ninja
          c-compiler: clang
          cxx-compiler: clang++
          source-dir: ./src
